# Generated by Django 5.0.6 on 2024-06-25 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_remove_customuser_api_key_remove_customuser_credits_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApiUsageLog",
        ),
    ]
