# Generated by Django 5.0.6 on 2024-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_delete_apiusagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="consent_personal_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="consent_service_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="consent_voice_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sms_marketing",
            field=models.BooleanField(default=False),
        ),
    ]
