# Generated by Django 5.0.6 on 2024-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_customuser_consent_personal_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile_images/"
            ),
        ),
    ]
