# Generated by Django 5.0.6 on 2024-07-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_subscriptionplan_paymenthistory_usersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("Pay As You Go", "Pay As You Go"),
                    ("BASIC", "Basic"),
                    ("ASSOCIATE", "Associate"),
                    ("PROFESSIONAL", "Professional"),
                ],
                max_length=20,
            ),
        ),
    ]
